services:
  - type: web
    name: broodinnox-dashboard
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    plan: free
    healthCheckPath: /
    autoDeploy: true
