services:
  - type: web
    name: broodinnox-pro
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: SESSION_SECRET
        generateValue: true
      - key: MQTT_BROKER
        value: mqtt://broker.hivemq.com
      - key: NODE_ENV
        value: production
